#!/bin/sh
f#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/juanfgs/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

nm-applet &
/usr/libexec/polkit-gnome-authentication-agent-1 &
feh --bg-scale Imágenes/Wallpapers/wallhaven-134014.jpg &
/usr/libexec/notification-daemon &
volumeicon &
conky -d
syndaemon -i 1.0 -K -R &
xfce4-power-manager &
cbatticon &
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/juanfgs/.fluxbox/log"

